[project]
name = "jack-analyzer"
version = "1.0.0"
requires-python = ">=3.8,<3.9"
dependencies = []

[dependency-groups]
dev = [
    "black>=24.8.0",
    "ruff>=0.11.8",
]

[tool.ruff.lint]
extend-select = ["B"]

[tool.black]
line-length = 150
